import type { Metadata } from "next";
import { Provider } from "@repo/ui/Provider";
import Navbar from "@repo/ui/CustomNavbar";
import "./globals.css"; // tailwindcss 활성화 위한 작업
import { SessionProvider, signOut } from "next-auth/react";
// TODO remove this after auth logic is implemented
import { navItems, profileMenuItems, userInfo } from "@repo/ui/mock";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // nextauth session
  const session = await auth();

  console.log( "session user!!",session);
  if( session?.user){
    userInfo.email = session.user.email ?? "";
    userInfo.name = session.user.name ?? "";
  }else{
    // test data reset
    userInfo.email = "";
    userInfo.name = "";
  }
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider
          themeProps={{ attribute: "class", defaultTheme: "dark", children }}
        >
          <SessionProvider session={session}>
            <Navbar
              navItems={navItems}
              menuItems={profileMenuItems}
              userInfo={userInfo}
              signOut={signOut}
              isLoggedIn={userInfo.email || userInfo.name ? true : false}
              // setIsLoggedIn={setIsLoggedIn}
            />
            <main>{children}</main>
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}
